name: krc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.8+1
environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  intl: 0.17.0
  logger: ^1.1.0
  shimmer: ^2.0.0
  provider: ^6.0.5
#  fluttertoast: any
  fluttertoast: ^8.1.1
  expandable: ^5.0.1
  pinch_zoom: ^1.0.0
  animations: ^2.0.7
  file_picker: ^5.2.4
  url_launcher: ^6.1.7
  progress_dialog: any
  image_picker: ^0.8.6
  carousel_slider: 4.2.1
  flutter_swiper: ^1.1.6
  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.2
#  firebase_core: ^2.4.1
#  firebase_messaging: ^14.2.1
  firebase_core: 2.11.0
  firebase_messaging: 14.5.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  awesome_notifications: ^0.7.4+1
  flutter_local_notifications: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_next_bold.ttf
        - asset: assets/fonts/avenir_next_demi_bold.ttf
        - asset: assets/fonts/avenir_next_demi_bold_italic.ttf
        - asset: assets/fonts/avenir_next_medium.ttf
        - asset: assets/fonts/avenir_next_regular.ttf






